# Generated by Django 5.2.5 on 2025-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agency', 'Agency'), ('dealer', 'Dealer')], default='user', max_length=20),
        ),
    ]
