# Generated by Django 5.2.5 on 2025-12-29 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('phone', models.IntegerField()),
                ('rera_cert_number', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(help_text='Your Society | Field working area')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user_auth.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlr_id', models.CharField(db_index=True, editable=False, help_text='Public ID like DLR-0001', max_length=20, unique=True)),
                ('phone', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealerWorkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=50, null=True)),
                ('Area', models.CharField(help_text='Your Society | Field working area')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_area', to='user_auth.dealer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('name', 'rera_cert_number'), name='unique_agency_fields'),
        ),
    ]
