# Generated by Django 5.2.5 on 2025-12-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_agency_agencyaddress_dealer_dealerworkingarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerworkingarea',
            old_name='Area',
            new_name='area',
        ),
    ]
