# Generated by Django 5.2.5 on 2025-12-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_rename_area_dealerworkingarea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
