# Generated by Django 5.2.5 on 2025-12-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_agency_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyaddress',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
