# Generated by Django 5.2.5 on 2025-12-29 21:47

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0004_rename_area_dealerworkingarea_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale')], max_length=20)),
                ('street_address', models.TextField()),
                ('unit_number', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('area_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_unit', models.CharField(choices=[('sq_ft', 'Square Feet'), ('sq_yards', 'Square Yards'), ('sq_m', 'Square Meters'), ('acres', 'Acres'), ('hectares', 'Hectares'), ('bigha', 'Bigha'), ('marla', 'Marla'), ('kanal', 'Kanal'), ('cents', 'Cents')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_cycle', models.CharField(choices=[('per_month', 'Per Month'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('per_year', 'Per Year')], max_length=20)),
                ('late_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('electricity_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contract_months', models.PositiveIntegerField(default=1)),
                ('kitchen_type', models.CharField(max_length=50)),
                ('bath_type', models.CharField(max_length=50)),
                ('number_of_baths', models.PositiveIntegerField()),
                ('number_of_beds', models.PositiveIntegerField()),
                ('available_from', models.DateField()),
                ('preferred_tenants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('other_details', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale')], max_length=20)),
                ('street_address', models.TextField()),
                ('unit_number', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('area_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_unit', models.CharField(choices=[('sq_ft', 'Square Feet'), ('sq_yards', 'Square Yards'), ('sq_m', 'Square Meters'), ('acres', 'Acres'), ('hectares', 'Hectares'), ('bigha', 'Bigha'), ('marla', 'Marla'), ('kanal', 'Kanal'), ('cents', 'Cents')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('down_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bhk', models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5+ BHK'), ('studio', 'Studio')], max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('facing', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20)),
                ('floor', models.CharField(max_length=10)),
                ('furnishing', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi Furnished'), ('fully_furnished', 'Fully Furnished')], max_length=20)),
                ('parking', models.CharField(choices=[('no_parking', 'No Parking'), ('1_car', '1 Car'), ('2_car', '2 Car'), ('3_car', '3+ Car'), ('bike_only', 'Bike Only'), ('both', 'Car & Bike')], max_length=20)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_by_type', models.CharField(choices=[('agency', 'Agency'), ('dealer', 'Dealer')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='user_auth.agency')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='user_auth.dealer')),
                ('property_rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='property_management.propertyforrent')),
                ('property_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='property_management.propertyforsale')),
            ],
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='sale_properties', through='property_management.PropertyListing', to='user_auth.agency'),
        ),
        migrations.AddField(
            model_name='propertyforsale',
            name='dealers',
            field=models.ManyToManyField(blank=True, related_name='sale_properties', through='property_management.PropertyListing', to='user_auth.dealer'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='agencies',
            field=models.ManyToManyField(blank=True, related_name='rent_properties', through='property_management.PropertyListing', to='user_auth.agency'),
        ),
        migrations.AddField(
            model_name='propertyforrent',
            name='dealers',
            field=models.ManyToManyField(blank=True, related_name='rent_properties', through='property_management.PropertyListing', to='user_auth.dealer'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('property_rent__isnull', False), ('property_sale__isnull', False), _connector='OR'), name='property_must_be_rent_or_sale'),
        ),
        migrations.AddConstraint(
            model_name='propertylisting',
            constraint=models.CheckConstraint(condition=models.Q(('agency__isnull', False), ('dealer__isnull', False), _connector='OR'), name='listing_must_have_agency_or_dealer'),
        ),
    ]
