# Generated by Django 5.2.5 on 2025-11-30 10:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('images', models.URLField(default='')),
                ('isAvailable', models.BooleanField(default=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
                ('rera_certificate', models.URLField(blank=True, default='Not Varified', null=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyAgentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('term_days', models.PositiveIntegerField(choices=[(365, '1 Year'), (730, '2 Years')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memberships', to='property_management.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPropertyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(choices=[(10, '10 Days'), (20, '20 Days'), (30, '30 Days')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_access', to='property_management.agencyagentmembership')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_access', to='property_management.property')),
            ],
            options={
                'unique_together': {('membership', 'property')},
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
                ('rera_certificate', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPropertyAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='property_management.agencypropertyaccess')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.agency')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_property_links', to='property_management.agencyagentmembership')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.dealer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.property')),
            ],
            options={
                'unique_together': {('dealer', 'agency', 'property')},
            },
        ),
        migrations.CreateModel(
            name='AgencyBillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('membership', 'Membership Fee'), ('property_subscription', 'Property Subscription')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.agency')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_management.dealer')),
            ],
        ),
        migrations.AddField(
            model_name='agencyagentmembership',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_memberships', to='property_management.dealer'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agents',
            field=models.ManyToManyField(through='property_management.AgencyPropertyAgents', to='property_management.dealer'),
        ),
        migrations.CreateModel(
            name='DealerProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('pending', 'Pending'), ('zeroclient', 'Zero Client')], db_index=True, default='zeroclient', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='0.15 → means 15%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('commission_final', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('is_commission_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_deals', to='property_management.dealer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_assignments', to='property_management.property')),
            ],
            options={
                'verbose_name': 'Dealer Deal',
                'verbose_name_plural': 'Dealer Deals',
                'unique_together': {('dealer', 'property')},
            },
        ),
        migrations.AddField(
            model_name='dealer',
            name='properties',
            field=models.ManyToManyField(through='property_management.DealerProperty', to='property_management.property'),
        ),
        migrations.CreateModel(
            name='AgencyProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('pending', 'Pending'), ('zeroclient', 'Zero Client')], db_index=True, default='zeroclient', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='0.15 → means 15%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('commission_final', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('is_commission_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_agency', to='property_management.agency')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_assignments', to='property_management.property')),
            ],
            options={
                'verbose_name': 'Agency Deal',
                'verbose_name_plural': 'Agency Deals',
                'unique_together': {('agency', 'property')},
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='properties',
            field=models.ManyToManyField(through='property_management.AgencyProperty', to='property_management.property'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyagentmembership',
            unique_together={('dealer', 'agency')},
        ),
    ]
