# Generated by Django 5.2.5 on 2025-12-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='user',
            new_name='dealer',
        ),
        migrations.AlterField(
            model_name='agency',
            name='properties',
            field=models.ManyToManyField(related_name='agencies', through='property_management.AgencyProperty', through_fields=('agency', 'property'), to='property_management.property'),
        ),
        migrations.AlterField(
            model_name='agencyproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deals', to='property_management.property'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='properties',
            field=models.ManyToManyField(related_name='dealers', through='property_management.DealerProperty', through_fields=('dealer', 'property'), to='property_management.property'),
        ),
        migrations.AlterField(
            model_name='dealerproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deals', to='property_management.property'),
        ),
    ]
