# Generated by Django 5.2.5 on 2025-12-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0005_alter_property_manager'),
        ('user_auth', '0010_remove_user_date_joined_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency',
            field=models.OneToOneField(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to='user_auth.user'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer',
            field=models.OneToOneField(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to='user_auth.user'),
        ),
        migrations.AlterField(
            model_name='property',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'role__in': ['dealer', 'agency']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propert_manager', to='user_auth.user'),
        ),
    ]
